/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.4
 * Generated at: 2026-03-09 04:15:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import uk.ac.ucl.view.TableData;
import java.util.List;
import uk.ac.ucl.view.TableData;
import java.util.List;
import java.util.ArrayList;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/searchBar.jspf", Long.valueOf(1773029695702L));
    _jspx_dependants.put("/buttonRow.jspf", Long.valueOf(1773029625713L));
    _jspx_dependants.put("/table.jspf", Long.valueOf(1773024698498L));
    _jspx_dependants.put("/header.jspf", Long.valueOf(1773011142108L));
    _jspx_dependants.put("/error.jsp", Long.valueOf(1773002570155L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("uk.ac.ucl.view.TableData");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    java.lang.Throwable exception = org.apache.jasper.runtime.JspRuntimeLibrary.getThrowable(request);
    if (exception != null) {
      response.setStatus(jakarta.servlet.http.HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
    }
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
 TableData table = (TableData) request.getAttribute("table");
String pageMode = (String) request.getAttribute("pageMode"); 
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("  ");
      out.write("<div>\n");
      out.write("    <title>Patient Data App</title>\n");
      out.write("    <link rel = \"stylesheet\" href = \"css/base.css\">\n");
      out.write("    <link rel = \"stylesheet\" href = \"css/tables.css\">\n");
      out.write("    <link rel = \"stylesheet\" href = \"css/buttons.css\">\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("  <div class=\"main\">\n");
      out.write("    <h3> Patient Data </h3>\n");
      out.write("    ");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("  <title>Error</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("  ");
 String errorMessage = (String) request.getAttribute("errorMessage"); 
      out.write('\n');
      out.write(' ');
      out.write(' ');
 if (errorMessage != null) { 
      out.write("\n");
      out.write("      <h2>Something went wrong</h2> \n");
      out.write("      <p class=\"error-message\">");
      out.print( errorMessage );
      out.write("</p>\n");
      out.write("      <a href=\"index.jsp\">Return to Home</a>\n");
      out.write("  ");
 } 
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("    ");
      out.write('\n');
      out.write('\n');
      out.write('\n');

List<String> names = table.getNames();
List<List<String>> columns = table.getColumns();

boolean hasData = columns != null 
  && !columns.isEmpty() 
  && !names.isEmpty() 
  && !columns.get(0).isEmpty();

int columnCount = names.size();
int rowCount = hasData ? columns.get(0).size() : 0;

      out.write("\n");
      out.write("\n");
      out.write("<div class = \"table-container\">\n");
      out.write("  ");
 if (!hasData) { 
      out.write("\n");
      out.write("  <p class = \"error-message\">Error: No results</p>\n");
      out.write("  ");
 } else { 
      out.write("\n");
      out.write("    <table>\n");
      out.write("      <thead>\n");
      out.write("        <tr>\n");
      out.write("          ");
 for (String name : names) { 
      out.write("\n");
      out.write("            <th class=\"top-header\">");
      out.print( name );
      out.write("</th>\n");
      out.write("          ");
 } 
      out.write("\n");
      out.write("        </tr>\n");
      out.write("      </thead>\n");
      out.write("      <tbody>\n");
      out.write("        ");
 for (int rowIndex = 0; rowIndex < rowCount; rowIndex++) { 
      out.write("\n");
      out.write("        <tr> \n");
      out.write("          ");
 for (int columnIndex = 0; columnIndex < columnCount; columnIndex++) {
            String value = columns.get(columnIndex).get(rowIndex);
            String classes = columnIndex == 0 ? "left-header" : ""; 
          
      out.write("\n");
      out.write("          <td class=\"");
      out.print( classes );
      out.write("\">\n");
      out.write("            ");
 if (names.get(columnIndex).equals("ID")) { 
      out.write("\n");
      out.write("            <a href = \"patient?id=");
      out.print( columns.get(columnIndex).get(rowIndex) );
      out.write("\">\n");
      out.write("              ");
      out.print( value );
      out.write("\n");
      out.write("            </a>\n");
      out.write("            ");
 } else { 
      out.write(" \n");
      out.write("              ");
      out.print( value );
      out.write("\n");
      out.write("            ");
 } 
      out.write(" \n");
      out.write("          </td>\n");
      out.write("          ");
 } 
      out.write(" \n");
      out.write("        </tr>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("      </tbody>\n");
      out.write("    </table>\n");
      out.write("  ");
 } 
      out.write("\n");
      out.write("</div>");
      out.write("\n");
      out.write("    ");
      out.write('\n');
      out.write('\n');
      out.write('\n');
 
String selectedColumn = request.getParameter("searchColumn");
String searchTerm = request.getParameter("searchTerm");

if (pageMode.equals("search")) {
  List<String> buttonNames = new ArrayList<>();
  buttonNames.add("ANY");
  buttonNames.addAll(table.getNames()); 
      out.write("\n");
      out.write("  <form action=\"/search\" method=\"get\" class=\"button-row\">\n");
      out.write("    ");
 for (String name : buttonNames) { 
      out.write("\n");
      out.write("      <button class=\"small-button\" type=\"submit\" name=\"searchColumn\" value=\"");
      out.print(name);
      out.write('"');
      out.write('>');
      out.write(' ');
      out.print( name );
      out.write(" </button>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("  </form> \n");
      out.write("\n");
      out.write("  ");
 if (selectedColumn != null && !selectedColumn.isEmpty()) { 
      out.write("\n");
      out.write("    <div class=\"button-row\">\n");
      out.write("      <form action=\"/search\" method=\"get\" class=\"inline-form\">\n");
      out.write("        <input type=\"hidden\" name=\"searchColumn\" value=\"");
      out.print( selectedColumn );
      out.write("\">\n");
      out.write("        <p class=\"small-button\">Searching in ");
      out.print( selectedColumn );
      out.write(" </p>\n");
      out.write("        <input type=\"text\" name=\"searchTerm\" placeholder=\"Enter search term\" value=\"");
      out.print( searchTerm != null ? searchTerm : "" );
      out.write("\">\n");
      out.write("        <button type=\"submit\" class=\"small-button\">Go</button>\n");
      out.write("      </form>\n");
      out.write("      <form action=\"/main\" method=\"get\" class=\"inline-form\">\n");
      out.write("        <button type=\"submit\" class=\"small-button\">Back</button>\n");
      out.write("      </form>\n");
      out.write("    </div>\n");
      out.write("  ");
 } 
      out.write('\n');
 } 
      out.write("\n");
      out.write("    ");
      out.write("<div class=\"button-row\">\n");
      out.write("  <form action=\"/search\" method=\"get\">\n");
      out.write("    <button type=\"submit\" class=\"button\">Search</button>\n");
      out.write("  </form>\n");
      out.write("  <form action=\"/sort\" method=\"get\">\n");
      out.write("    <button type=\"submit\" class=\"button\">Sort</button>\n");
      out.write("  </form>\n");
      out.write("  <form action=\"/new\" method=\"get\">\n");
      out.write("    <button type=\"submit\" class=\"button\">New</button>\n");
      out.write("  </form>\n");
      out.write("  <form action=\"/import\" method=\"get\">\n");
      out.write("    <button type=\"submit\" class=\"button\">Import</button>\n");
      out.write("  </form>\n");
      out.write("  <form action=\"/export\" method=\"get\">\n");
      out.write("    <button type=\"submit\" class=\"button\">Export</button>\n");
      out.write("  </form>\n");
      out.write("  <form action=\"/undo\" method=\"get\">\n");
      out.write("    <button type=\"submit\" class=\"button\">Undo</button>\n");
      out.write("  </form>\n");
      out.write("  <form action=\"/redo\" method=\"get\">\n");
      out.write("    <button type=\"submit\" class=\"button\">Redo</button>\n");
      out.write("  </form>\n");
      out.write("  <form action=\"/statistics\" method=\"get\">\n");
      out.write("    <button type=\"submit\" class=\"button\">Statistics</button>\n");
      out.write("  </form>\n");
      out.write("  <form action=\"/graphs\" method=\"get\">\n");
      out.write("    <button type=\"submit\" class=\"button\">Graphs</button>\n");
      out.write("  </form>\n");
      out.write("  <form action=\"/main\" method=\"get\">\n");
      out.write("    <button type=\"submit\" class=\"button\">Back</button>\n");
      out.write("  </form>\n");
      out.write("</div>");
      out.write("\n");
      out.write("  </div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
