/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.4
 * Generated at: 2026-03-16 15:27:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import java.util.ArrayList;
import uk.ac.ucl.view.TableData;

public final class table_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("uk.ac.ucl.view.TableData");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

  // Fetch and unpack TableData from request
  TableData table = (TableData) request.getAttribute("table");
  String pageMode = (String) request.getAttribute("pageMode");
  String key = (String) request.getAttribute("key");

  int currentPage = (int) request.getAttribute("page");
  int pageSize = (int) request.getAttribute("pageSize");
  int pageTotal = (int) request.getAttribute("pageTotal");


  List<String> names = table.names();
  List<List<String>> columns = table.columns();
  
  // Validate retrieved table data
  boolean hasData = columns != null
  && !columns.isEmpty()
  && !names.isEmpty()
  && !columns.get(0).isEmpty();
  int columnCount = names.size();
  int rowCount = hasData ? columns.get(0).size() : 0;
  
  // Assumption: pageMode equal to 'edit' -> 'row' intialized
  Integer row = (Integer) request.getAttribute("row");
  // Display error message if the table is missing data
if (!hasData) { 
      out.write("\n");
      out.write("<p class = \"error-message\">Error: No results</p>\n");
 } else { 
      out.write('\n');
      out.write("\n");
      out.write("<div class = \"table-container\">\n");
      out.write("  <table>\n");
      out.write("    <thead>\n");
      out.write("      <tr>\n");
      out.write("        ");
      out.write("\n");
      out.write("        <th class=\"top-header left-header\">Row</th>\n");
      out.write("        ");
 for (String name : names) { 
      out.write("\n");
      out.write("        <th class=\"top-header\">");
      out.print( name );
      out.write("</th>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("      </tr>\n");
      out.write("    </thead>\n");
      out.write("    <tbody>\n");
      out.write("      ");
      out.write("\n");
      out.write("      ");
 for (int rowIndex = 0; rowIndex < rowCount; rowIndex++) { 
      out.write("\n");
      out.write("      <tr>\n");
      out.write("        <td class=\"left-header\"> ");
      out.write("\n");
      out.write("          ");
      out.write("\n");
      out.write("          ");
 if ("edit".equals(pageMode)) { 
      out.write("\n");
      out.write("          <span class=\"row-link\">");
      out.print(1+row);
      out.write("</span>\n");
      out.write("          ");
 } else { 
      out.write("\n");
      out.write("          ");
      out.write("\n");
      out.write("          <a href = \"");
      out.print(request.getContextPath() + "/edit?row=" + (rowIndex+pageSize*(currentPage-1)));
      out.write("\" class=\"row-link\">");
      out.print(1+rowIndex+pageSize*(currentPage-1));
      out.write("</a>\n");
      out.write("          ");
 } 
      out.write("\n");
      out.write("        </td>\n");
      out.write("        ");
      out.write("\n");
      out.write("        ");
 for (int columnIndex = 0; columnIndex < columnCount; columnIndex++) {
          String value = columns.get(columnIndex).get(rowIndex);
        
      out.write("\n");
      out.write("        <td>\n");
      out.write("          ");
      out.write("\n");
      out.write("          ");
      out.write("\n");
      out.write("          ");
 if (names.get(columnIndex).equals(key) && !"edit".equals(pageMode)) { 
      out.write("\n");
      out.write("          <a href = \"");
      out.print(request.getContextPath() + "/edit?row=" + (rowIndex+pageSize*(currentPage-1)));
      out.write("\">\n");
      out.write("            ");
      out.print( value );
      out.write("\n");
      out.write("          </a>\n");
      out.write("          ");
 } else { 
      out.write("\n");
      out.write("          ");
      out.print( value );
      out.write("\n");
      out.write("          ");
 } 
      out.write("\n");
      out.write("        </td>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("      </tr>\n");
      out.write("      ");
 } 
      out.write("\n");
      out.write("    </tbody>\n");
      out.write("  </table>\n");
      out.write("</div>\n");
 } 
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
